services:
  app:
    image: ghcr.io/zwluoqi/chatgpt2api-go:latest
    container_name: chatgpt2api-go
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json:ro
